export const weatherActions = {
  LOAD_CITY_WEATHER: "LOAD_CITY_WEATHER",
  LOAD_CITY_WEATHER_FORECAST: "LOAD_CITY_WEATHER_FORECAST",
};

export const searchActions = {
  SET_SELECTED_CITY_FROM_SEARCH: "SET_SELECTED_CITY_FROM_SEARCH",
};
