export const lightTheme = {
  body: "#ffffff",
  text: "#363537",
  toggleBorder: "#FFF",
  navbarBackground: "#e3f2fd",
  gradient: "linear-gradient(#39598A, #79D7ED)",
  buttonBorderColor: "lightblue",
  buttonColorHover: "lightblue",
  navbarTitleColor: "black",
  buttonTextColor: "black",
  searchboxColor: "#e3f2fd",
  searchboxInputColor: "white",
  searchboxPlaceholderColor: "black",
  searchboxInputTextColor: "black",
  searchboxIconColor: "grey",
  buttonBackground: "#e3f2fd",
  cityItemFontColor: "black",
};

export const darkTheme = {
  body: "#363537",
  text: "#736d6d",
  toggleBorder: "#6B8096",
  navbarBackground: "gray",
  gradient: "linear-gradient(#091236, #1E215D)",
  buttonBorderColor: "#5C5C5C",
  buttonColorHover: "#5C5C5C",
  navbarTitleColor: "#FFFFFF",
  buttonTextColor: "#FFFFFF",
  searchboxColor: "#5C5C5C",
  searchboxInputColor: "grey",
  searchboxPlaceholderColor: "white",
  searchboxInputTextColor: "white",
  searchboxIconColor: "white",
  buttonBackground: "gray",
  cityItemFontColor: "#736d6d",
};
